### ISSUE TITLE
How to prevent downcast to scalar values

### ISSUE THREAD

**Issue by dselivanov** [dbdahl/rscala-mirror#1]
Suppose my scala function has signature:
```scala
def fun(input: Array[String]) = {
 ...
}
```

Then I pass single scalar value from R:
```r
s$fun("A")
```

Somewhere in the middle downcast to scalar happens, so I'm getting error:
> <console>:12: error: type mismatch;
 found   : String
 required: Array[String]

How to prevent such conversion and treat scalars as arrays with single element?

**Comment by dbdahl** [comment]
Two options:

1. You call the function with the argument 'length.one.as.vector=TRUE'.
2. Or, if you perfer to set it globally for that interpreter, you can use the scalaSettings function.

Both are illustrated below.

```R
library(rscala)

s <- scala()

s %@% '
  object Test {
    def fun(input: Array[String]) = {
      input.length
    }
  }
'

e <- s$do("Test")

e$fun("a",length.one.as.vector=TRUE)

scalaSettings(s,length.one.as.vector=TRUE)

e$fun("a")
```

**Comment by dselivanov** [comment]
Thanks, `length.one.as.vector=TRUE` is what I looked for.
